language: c++
dist: bionic
sudo: required
cache:
    directories:
        - build

before_install: ./script/dependency.sh
script: make test
after_success:
    - bash <(curl -s https://codecov.io/bash)
after_failure:
    - make clean
