#!/bin/bash
set -e

for cat in src/*/
do
    [ ! -d "$cat" ] && continue
    echo "Testing category $cat ..."
    (
        cd "$cat"
        for code in *.cpp
        do
            [ ! -f "$code" ] && continue
            echo "Testing code $code ..."
            bn=$(basename -s .cpp "$code")
            g++ -O2 -Wall -ggdb -fsanitize=undefined,address "$code" -ftest-coverage -fprofile-arcs -o $bn.out
            ./$bn.out
            gcov -n -o . ./$code > /dev/null
        done
    )
done
